import os
import httpx
from dotenv import load_dotenv

load_dotenv()

PRIORITY_MAP = {
    "critical": 1,
    "high":     2,
    "medium":   3,
    "low":      4,
}


class TestRailClient:

    def __init__(self):
        self.base_url = os.getenv("TESTRAIL_BASE_URL", "http://localhost:4002")
        self.email    = os.getenv("TESTRAIL_EMAIL")
        self.api_key  = os.getenv("TESTRAIL_API_KEY")
        self.auth     = (self.email, self.api_key)
        self.headers  = {"Content-Type": "application/json"}

    def add_case(self, section_id: int, title: str, steps: list,
                 expected: str, priority: str) -> dict:
        """Push a single new test case to TestRail."""
        url = f"{self.base_url}/index.php/api/v2/add_case/{section_id}"
        payload = {
            "title":       title,
            "template_id": 2,
            "custom_preconds": "Generated by AI Agent",
            "custom_steps_separated": [
                {"step": step, "expected": expected} for step in steps
            ],
            "priority_id": PRIORITY_MAP.get(priority.lower(), 3),
        }
        response = httpx.post(url, json=payload, auth=self.auth, headers=self.headers)
        response.raise_for_status()
        return response.json()

    def add_cases_bulk(self, section_id: int, test_cases: list) -> list:
        """Push a list of new test cases. Returns list of created case IDs."""
        created_ids = []
        for tc in test_cases:
            result = self.add_case(
                section_id=section_id,
                title=tc.get("title", ""),
                steps=tc.get("steps", []),
                expected=tc.get("expected", ""),
                priority=tc.get("priority", "medium"),
            )
            created_ids.append(result.get("id"))
        return created_ids

    def get_cases(self, project_id: int, suite_id: int = None,
                  section_id: int = None) -> list:
        """Fetch test cases for a project, optionally filtered by suite/section."""
        if not project_id:
            raise ValueError("TestRail project_id is required to fetch cases")
        url    = f"{self.base_url}/index.php/api/v2/get_cases/{project_id}"
        params = {}
        if suite_id is not None:
            params["suite_id"]   = suite_id
        if section_id is not None:
            params["section_id"] = section_id
        response = httpx.get(url, params=params, auth=self.auth, headers=self.headers)
        response.raise_for_status()
        return response.json()

    def update_case(
        self,
        case_id: int,
        title: str = None,
        preconditions: str = None,
        steps=None,
        expected: str = None,
    ) -> dict:
        """
        Update an existing TestRail case with improved content.

        `steps` accepts three formats:

        Format 1 (PRIMARY) - list of {"action": ..., "expected": ...} dicts:
            Each dict maps to a TestRail step with its own per-step expected result.
            [{"action": "Navigate to login page", "expected": "Page loads"},
             {"action": "Click Login",             "expected": "Error shown"}]

        Format 2 (legacy) - list of plain strings:
            ["Navigate to login page", "Click Login"]
            Overall `expected` is attached to the last step only.

        Format 3 (legacy) - dict {action_text: per_step_expected}:
            {"Navigate to login page": "Page loads", "Click Login": "Error shown"}
        """
        if not case_id:
            raise ValueError("TestRail case_id is required for update_case")

        url     = f"{self.base_url}/index.php/api/v2/update_case/{case_id}"
        payload = {}

        if title is not None:
            payload["title"] = title
        if preconditions is not None:
            payload["custom_preconds"] = preconditions
        if steps is not None:
            payload["custom_steps_separated"] = _build_steps_payload(steps, expected)
        if expected is not None:
            payload["custom_expected"] = expected

        response = httpx.post(url, json=payload, auth=self.auth, headers=self.headers)
        response.raise_for_status()
        return response.json()


def _build_steps_payload(steps, overall_expected: str = "") -> list:
    """
    Convert any supported steps format into the TestRail
    custom_steps_separated payload: [{"step": ..., "expected": ...}, ...]
    """
    if not steps:
        return []

    # Format 1: list of {"action": ..., "expected": ...} dicts  <-- PRIMARY
    if isinstance(steps, list) and steps and isinstance(steps[0], dict):
        result = []
        for item in steps:
            action   = str(item.get("action", item.get("step", ""))).strip()
            expected = str(item.get("expected", "")).strip()
            if action:
                result.append({"step": action, "expected": expected})
        return result

    # Format 2: list of plain strings
    if isinstance(steps, list):
        total  = len(steps)
        result = []
        for idx, step_text in enumerate(steps):
            step_text = str(step_text).strip()
            if not step_text:
                continue
            step_expected = (overall_expected or "") if idx == total - 1 else ""
            result.append({"step": step_text, "expected": step_expected})
        return result

    # Format 3: dict {action_text: per_step_expected}
    if isinstance(steps, dict):
        return [
            {"step": str(k).strip(), "expected": str(v).strip()}
            for k, v in steps.items() if str(k).strip()
        ]

    return []